name: app_gateway
description: The API handler for web app gateway requests to CloudFront.
version: 1.0.0
homepage: https://my-great.app
publish_to: none

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  json_annotation: ^4.4.0
  aws_dynamodb_api: ^1.2.0
  aws_lambda_dart_runtime: ^1.1.0
  app_shared:
    path: ../../shared

dev_dependencies:
  test: ^1.20.2
  lints: ^1.0.1
  mocktail: ^0.3.0
  analyzer: ^3.4.1
  build_runner: ^2.1.8
  json_serializable: ^6.1.5
