name: app_todos
description: The Apps Todo CRUD operations API endpoints.
version: 1.0.0
homepage: https://my-great.app
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  json_annotation: ^4.6.0
  aws_dynamodb_api: ^1.2.0
  aws_lambda_dart_runtime: ^1.1.0
  app_shared:
    path: ../../shared

dev_dependencies:
  test: ^1.21.5
  lints: ^2.0.0
  mocktail: ^0.3.0
  analyzer: ^4.7.0
  build_runner: ^2.2.0
  json_serializable: ^6.3.1
