name: app_meta
description: The Apps Meta API endpoints.
version: 1.0.0
homepage: https://my-great.app
publish_to: none

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  aws_lambda_dart_runtime: ^1.1.0
  app_shared:
    path: ../../shared

dev_dependencies:
  test: ^1.20.2
  mocktail: ^0.3.0
  build_runner: ^2.1.8
