name: app_meta
description: The Apps Meta API endpoints.
version: 1.0.0
homepage: https://my-great.app
publish_to: none

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  aws_lambda_dart_runtime: ^1.1.0
  app_shared:
    path: ../../shared

dev_dependencies:
  test: ^1.25.0
  mocktail: ^1.0.2
  build_runner: ^2.4.7
