name: app_shared
description: Shared models and components for the app.
version: 1.0.0
homepage: https://my-great.app
publish_to: none

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  amazon_cognito_identity_dart_2: ^3.6.0
  aws_budgets_api: ^2.0.0
  aws_ce_api: ^2.0.0
  aws_cur_api: ^2.0.0
  aws_dynamodb_api: ^2.0.0
  endaft_core: 0.0.4-dev.8
  equatable: ^2.0.5
  geography: ^2.0.1
  http: ">=0.13.1 <2.0.0"
  injector: ^3.0.0
  json_annotation: ^4.8.1
  meta: ^1.11.0
  tuple: ^2.0.2

dev_dependencies:
  analyzer: ^6.3.0
  build_runner: ^2.4.7
  coverage: ^1.7.2
  endaft: ^0.0.3-dev.31
  json_serializable: ^6.7.1
  lints: ^3.0.0
  mocktail: ^1.0.2
  test: ^1.25.0
