name: app_shared
description: Shared models and components for the app.
version: 1.0.0
homepage: https://my-great.app
publish_to: none

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  amazon_cognito_identity_dart_2: ^1.0.5
  meta: ^1.7.0
  http: ^0.13.4
  tuple: ^2.0.0
  lipsum: ^1.0.1
  injector: ^2.0.0
  equatable: ^2.0.3
  geography: ^1.1.3
  json_annotation: ^4.4.0
  aws_dynamodb_api: ^1.2.0
  aws_budgets_api: ^1.2.0
  aws_ce_api: ^1.2.0
  aws_cur_api: ^1.2.0
  endaft_core: ^0.0.2-dev.31

dev_dependencies:
  test: ^1.20.2
  lints: ^1.0.1
  mocktail: ^0.3.0
  analyzer: ^3.4.1
  coverage: ^1.2.0
  build_runner: ^2.1.8
  json_serializable: ^6.1.5
