name: app_shared
description: Shared models and components for the app.
version: 1.0.0
homepage: https://my-great.app
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  amazon_cognito_identity_dart_2: ^3.0.3
  aws_budgets_api: ^1.2.0
  aws_ce_api: ^1.2.0
  aws_cur_api: ^1.2.0
  aws_dynamodb_api: ^1.2.0
  endaft_core: 0.0.3-dev.42
  equatable: ^2.0.5
  geography: ^1.1.5
  http: ^0.13.5
  injector: ^2.0.0
  json_annotation: ^4.7.0
  lipsum: ^1.0.1
  meta: ^1.8.0
  tuple: ^2.0.1

dev_dependencies:
  analyzer: ^5.2.0
  build_runner: ^2.3.2
  coverage: ^1.6.1
  endaft: ^0.0.3-dev.31
  json_serializable: ^6.5.4
  lints: ^2.0.1
  mocktail: ^0.3.0
  test: ^1.21.7
